[env:waveshare_c6_lcd]
platform = espressif32 @ 6.8.0
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.flash_size = 2MB
board_upload.flash_size = 2MB
board_build.partitions = partitions_2mb.csv
lib_deps = 
    lovyan03/LovyanGFX@^1.2.19
build_flags = 
    -D LGFX_USE_V1=1
    -D ARDUINO_ARCH_ESP32=1
    ; -D CONFIG_ESP_WIFI_ENABLE_WPA3_SAE=0
    -D CONFIG_ESP_WIFI_STA_ENABLE_PMF=1
board_build.sdkconfig.defaults = sdkconfig.defaults
monitor_filters = esp32_exception_decoder, time